### ISSUE TITLE
スコアの表示

### ISSUE THREAD

**Issue by dashimaki360** [dashimaki360/turtle_war#9]
ターミナル上でもいいし
GAZEBOでもいいし
ファイルが残るようにするとより安全かも

**Comment by t-kishi** [comment]
新入社員の岸です．よろしくお願いします．

**Comment by dashimaki360** [comment]
よろしくー
うごかしてみたりした?

**Comment by t-kishi** [comment]
お疲れ様です！
とりあえずREADME.mdをやってみました．
VMWareに新しくUbuntu14.04環境ですが，以下の現象がありました．

１．インストール時
　$ clone https://github.com/dashimaki360/turtle_war.git
→$ git clone https://github.com/dashimaki360/turtle_war.git
としないとエラーとなる

２．$ roslaunch turtle_war war_field.launchが正常起動しない
初回起動時，上記コマンド起動がエラーとなりました．
Gazeboを一度単体起動した後再度コマンドを打ったところ，起動できました．

３．roslaunch turtle_war minimal.launchが正常起動しない
初回起動時，上記コマンド起動がエラーとなりました．
再起動後再度コマンドを打ったところ，起動できました．

**Comment by dashimaki360** [comment]
ありがとー

すみません　READMEを更新サボってました。。。

多分gazeboの再起動でなおったのは初回はモデルのダウンロードがしばらくかかるからやと思います。
